server:
  port: 2020
spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:mysql://localhost:3306/bookings?createDatabaseIfNotExist=true
    username: root
    password: manager
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


