spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes[0]:
            id: booking-service
            uri: lb://booking-service
            predicates:
              - Path=/booking/**
          routes[1]:
            id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payment/**
server:
  port: 8765