spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: booking-route
          uri: http://booking-service
          predicates: [ Path=/bookings/** ]
        - id: payment-route
          uri: http://payment-service
          predicates: [ Path=/payments/** ]

server:
  port: 8765