spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes[0]:
            id: booking-service
            uri: lb://booking-service
            predicates:
              - Path=/bookings/**
            filters:
              - name: CircuitBreaker
                args:
                  name: bookingServiceCircuitBreaker
                  fallbackUri: forward:/bookingServiceFallBack
          routes[1]:
            id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/payments/**
            filters:
              - name: CircuitBreaker
                args:
                  name: paymentServiceCircuitBreaker
                  fallbackUri: forward:/paymentServiceFallBack
server:
  port: 8765