server:
  port: 2021
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payments?createDatabaseIfNotExist=true
    username: root
    password: manager
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

stripe:
  key: sk_test_51S6bysEntyGJ5KmQuUw9CEn7OvK1FwW14j6TixM4Gtr3tU0pwmG4ILG9iyZ8zBVZE0fFqnenOCR9JHO9MkI9re5b002R2a2ET9

dodo:
  key: ftilVWCrq6fbPJw-.SpUTsdYcOaLTvWhMYJ6P16EzngNnMr-GuqgE29G6pH9RfvCv
  base-url: https://test.dodopayments.com

  #key: ftilVWCrq6fbPJw-.SpUTsdYcOaLTvWhMYJ6P16EzngNnMr-GuqgE29G6pH9RfvCv