version: '3.9'
services:
  schema-registry:
    image: confluentinc/cp-schema-registry:7.0.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - kafka-broker-1
      - kafka-broker-2
      - kafka-broker-3
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE-CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'PLAINTEXT://kafka-broker-1:19092,PLAINTEXT://kafka-broker-2:19093,PLAINTEXT://kafka-broker-3:19094'
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_DEBUG: 'true'

  kafka-broker-1:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker-1
    ports:
      - "19092:19092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, LISTENER_LOCAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-1:19092,LISTENER_LOCAL://localhost:19092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-1:19092,LISTENER_LOCAL://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    volumes:
      - "./volumes/kafka-broker-1/data:/var/lib/kafka/data"

  kafka-broker-2:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker-2
    ports:
      - "19093:19093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, LISTENER_LOCAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-2:19093,LISTENER_LOCAL://localhost:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-2:19093,LISTENER_LOCAL://localhost:19093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    volumes:
      - "./volumes/kafka-broker-2/data:/var/lib/kafka/data"

  kafka-broker-3:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka-broker-3
    ports:
      - "19094:19094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT, LISTENER_LOCAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka-broker-3:19094,LISTENER_LOCAL://localhost:19094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker-3:19094,LISTENER_LOCAL://localhost:19094
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_COMPRESSION_TYPE: producer
    volumes:
      - "./volumes/kafka-broker-3/data:/var/lib/kafka/data"

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    container_name: kafka-manager
    restart: always
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"