spring:
  application:
    name: UserRegistration

  datasource:
    username: root
    password: manager
    url: jdbc:mysql://localhost:3306/user_registration?createDatabaseIfNotExist=true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
